# Generated by Django 4.0.3 on 2022-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('category', models.CharField(max_length=30)),
                ('descriotion', models.TextField()),
            ],
        ),
    ]
