# Generated by Django 4.0.3 on 2022-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_Phone', models.CharField(max_length=200)),
                ('addres', models.CharField(max_length=200)),
                ('number_order', models.CharField(max_length=200)),
                ('count_order', models.CharField(max_length=200)),
            ],
        ),
    ]
