# Generated by Django 4.0.3 on 2022-04-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='like_product',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
