# Generated by Django 4.0.3 on 2022-04-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_userprofile_like_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id']},
        ),
    ]
